sudo: required
os:
  - linux
  dist: Xenial
  - osx
   osx_image: xcode7.2
language: python
python:
  - "3.6"
  - "3.5"
  - "3.7"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

install:
  - pip install -r requirements.txt
  - python setup.py install 
  - bash install/user_install.sh
  - python install/align_data_sources.py
  script: 
  - python3 unit_test/scrape_test.py
  - streamlit run app.py
after_success:
  - coveralls
